### get account
GET http://localhost:8080/account?user_Id=1049
Content-Type: application/json



### create account
POST http://localhost:8080/account
Content-Type: application/json

{
  "userId": "a",
  "initialBalance": "500"
}

### delete account
DELETE http://localhost:8080/account
Content-Type: application/json

{
  "userId": 1,
  "AccountNumber": 1000000003
}